spring:
  application:
    name: "@artifactId@"
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 1MB
      location: ${java.io.tmpdir}
      file-size-threshold: 0
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 356d
  messages:
    basename: messages/messages
    cache-duration: 1d
  jackson:
    locale: zh
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  thymeleaf:
    mode: html
  cache:
    ehcache:
      config: classpath:config/ehcache.xml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
## mybatis
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  typeAliasesPackage: net.dreamlu.**.model
  mapper-locations: classpath:net/dreamlu/**/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_null
      table-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
